# Generated by Django 5.1.14 on 2025-11-19 19:41

import django.core.validators
import django.db.models.deletion
import university_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('credits', models.PositiveSmallIntegerField(verbose_name='Кредиты (ECTS)')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Обучается'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Выпускник')], default='active', max_length=20, verbose_name='Статус')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[university_app.models.validate_gpa], verbose_name='GPA')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время экзамена')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('overdue', 'Просрочено'), ('canceled', 'Отменено')], default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='university_app.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('attended', models.BooleanField(default=True, verbose_name='Явка')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.student')),
            ],
            options={
                'verbose_name': 'Результат экзамена',
                'verbose_name_plural': 'Результаты экзаменов',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='university_app.ExamResult', to='university_app.student', verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('position', models.CharField(choices=[('assistant', 'Ассистент'), ('lecturer', 'Старший преподаватель'), ('associate_professor', 'Доцент'), ('professor', 'Профессор')], max_length=50, verbose_name='Должность')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_app.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='university_app.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Дата записи')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка (0-100)')),
                ('passed', models.BooleanField(default=False, verbose_name='Зачтено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'unique_together': {('day_of_week', 'start_time', 'room')},
            },
        ),
    ]
